### PR TITLE
Remove ImGuiSelectableFlags_ enum name. Add ImDrawList methods. Add ImColor struct.

### PR DESCRIPTION
**Pull request by MrSmith33**
Also a newer version of cimgui should be included once pulled.

### CODE REVIEW

**Comment by MrSmith33** [comment]
Thought, that multiple alias this was already there

**Comment by MrSmith33** [comment]
ping

**Comment by extrawurst** [comment]
Thank you very much!

**Comment by MrSmith33** [comment]
You are welcome =)

P.S. Should we _port_ the whole thing to D?

**Comment by extrawurst** [comment]
@MrSmith33 We could but I think it is a lot more working keeping up to date than a simple binding/wrapper

**Pull request merged**
