### PR TITLE
Update the API to follow cImGui v1.53.1

### LINKED ISSUE #17: Support `cimgui` v1.53.1
Hi,

I quickly tried using the demo with `cimgui` v1.53.1, and I had weird missing symbol errors, it'd be nice to bring the D bindings up to speed with upstream `ImGui`/`cimgui`.

### PR DESCRIPTION
**Pull request by lenormf**
I've started the work to migrate to v1.53.1, I could successfully run the demo using this patch. Comparisons between what's supported by `cimgui` and this implementation of the bindings will probably have to be made, in order to avoid blindspots (some things might not be supported yet).

Closes #17.

### CODE REVIEW

**Comment by extrawurst** [comment]
can you update this branch to the latest PR being merged, so that we can see travis running through successfully?

**Comment by lenormf** [comment]
Done!

**Comment by extrawurst** [comment]
Here we go, its green. You did not update cimgui (the submodule) to the version you made it compatible with, right? Can you do that, then we are awesome :)
You can also update the readme to reflect the version.

**Comment by lenormf** [comment]
I'm waiting to make sure that the entire API is being correctly bound. I might do it, just not sure when. Once that's done, I'll add a commit to update the README and the submodules' configuration.

**Comment by extrawurst** [comment]
ok then I'll keep this PR open until then. the submodule should reflect the version used here. Thanks already in advance for your big help!

**Comment by lenormf** [comment]
I finished migrating the demo to have a 1:1 equivalence with the C++ one. There might still be some uncovered bugs somewhere (e.g. API changes from the C bindings), but I think most of the work is done now.

The build error is due to a network error on Travis' side, the build probably works on `gdc` (haven't tested).

**Comment by extrawurst** [comment]
Thanks so much! lgtm

**Comment by lenormf** [comment]
Will you update [the `dub` package](https://code.dlang.org/packages/derelict-imgui) to this version?

**Comment by extrawurst** [comment]
done: https://github.com/Extrawurst/DerelictImgui/releases/tag/v0.10.0

**Pull request merged**
