### PR TITLE
Fix issues that prevent building the library and the demo

### PR DESCRIPTION
**Pull request by lenormf**
HTH.

### CODE REVIEW

**Comment by extrawurst** [comment]
Awesome thanks! Can you update `.travis.yml` to the latest compilers that should be supported, I am fine with cutting off older versions of the compilers if necessary but the travis config should reflect that.

**Comment by lenormf** [comment]
I hope I understand what's asked properly, I added my version of `dmd` that could compile the code successfully and updated the version of `ldc` that built fine in Travis.

**Comment by extrawurst** [comment]
My idea was that travis would become green for this branch, that there is no compiler left in the `.travis.yml` that does not work with these var_arg changes. is there no `gdc` version supporting this anymore?

**Comment by lenormf** [comment]
I added some fixes, the code compiles on most compiler versions, but the others are beyond saving I think. All the info is in the commit messages.

**Comment by extrawurst** [comment]
Thank you so much! Really great work!

**Pull request merged**
